#! /bin/bash

# change directory to script location
cd "$(dirname "$0")"

# some vars
project="$(pwd)"
target_name="x86_64-bit_os"
target=$project/$target_name.json

# Build everyhing
./build
if [ $? -ne 0 ]; then
	echo "failed build"
	exit
fi

# Run the kernel
cd $project/kernel
bootimage run --target $target -- -m 1G -serial stdio || echo "failed to run kernel"

