#!/bin/bash

# add nightly support
rustup override add nightly

# install build dependencies
cargo install cargo-xbuild
cargo install bootimage --version "^0.7.7"

# add rust components
rustup component add rust-src
rustup component add llvm-tools-preview

